### ISSUE TITLE
HTML extract (feature request)

### ISSUE THREAD

**Issue by ej159** [e-zz/logseq-pdf-extract#16]
I would like to be able to do the following:

- Save a webpage to Zotero
- Open the Snapshot (a HTML file) in Logseq
- Take linked extracts of the HTML file in Logseq (as this plugin makes possible with pdfs).

It really doesn't feel that far from being possible, especially considering there is [an integrated HTML viewer for logseq](https://github.com/lee88688/logseq-mhtml-view-plugin)

**Comment by e-zz** [comment]
Hi, thanks for the idea. It's indeed nice if one can annotate diverse files than just PDFs. Sorry due to the limited time I can devote to the plugin, I am afraid I won't have the time to do this. 
One thing might be possible is to import html files (actually uri links to those files) from Zotero. Please tell me if you think it's useful :)
